MAIL_USERNAME=johnwisker27@gmail.com
MAIL_PASSWORD=yufqauitrorrsztm

cloudinary.cloud-name=dkgsu1oq0
cloudinary.api-key=489791986711537
cloudinary.api-secret=T-MOZpq4e3u9rx5X7Uuots_LqjI

GROQ_API_KEY=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

TESSERACT_DATAPATH=C:/Program Files/Tesseract-OCR/tessdata